name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Test against Node.js 20.x

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
        npm install -D @babel/plugin-proposal-private-property-in-object
        npm install -g react-snap
    - name: Build and Statically Render
      run: |
        export PATH="$PATH:$(npm bin)"
        npm run build
        react-snap
      env:
        NODE_ENV: production
    - name: Display package.json
      run: cat package.json
    - name: List installed packages
      run: npm list --depth=0