name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]  # Test against multiple versions if needed

    steps:
    - uses: actions/checkout@v3  # Latest version compatible with Node.js 20
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # Latest version compatible with Node.js 20
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and Statically Render
      run: npm run predeploy
      env:
        NODE_ENV: development
