name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3  # Update to the latest version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # Update to the latest version
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and Statically Render
      run: npm run predeploy
      env:
        NODE_ENV: development
